---
- name: Tomcat Deployment
  hosts: tom
  become: true
  vars:
    URL_ART: " artifact URL "
  tasks:
    - name: Download Artifact
      get_url:
        url: "{{ URL }}"
        dest: ./apache/webapps/

    -  name: Start Catalina
       shell: sh /opt/apache/bin/catalina.sh start
...       
