---
- name: Tomcat Deployment
  hosts: tom
  become: true
  tasks:
    -  name: Copy Artifact
       copy:
         src: ./target/studentapp-2.2.war
         dest: /opt/apache/webapp/studentapp-2.2.war

    -  name: Start Catalina
       shell: sh /opt/apache/bin/catalina.sh start
...       
