---
- name: Tomcat Deployment
  hosts: tom
  become: true
  vars:
    URL_ART: " Artifact URL "
  tasks:
    - name: Download Artifact
      get_url:
        url: "{{ URL_ART }}"
        dest: ./apache-tomcat-8.5.78/webapps/

    -  name: Start Catalina
       shell: sh ./apache-tomcat-8.5.78/bin/catalina.sh start
...       
