---
- name: Tomcat Deployment
  hosts: Tom
  become: true
  tasks:
    -  name: Copy Artifact
       copy:
         src: /opt
         dest: /opt/apache/webapp/

    -  name: Start Catalina
       shell: sh /opt/apache/bin/catalina.sh start
...       
